### ISSUE TITLE
send_email.py doesn't work

### ISSUE THREAD

**Issue by rh3xp** [vprusso/youtube_tutorials#1]
It always shows "Email failed to send error."
![new](https://user-images.githubusercontent.com/11832723/34082994-ab1a1e48-e38e-11e7-9267-dceea53fcafe.png)

**Comment by vprusso** [comment]
Hey Parth, 
It would be helpful to me if you could print the error output as to what Python deems to be the issue. The way I would suggest you do this is to eliminate the "try/except" statement and see where, specifically, the script is failing you. If you could follow-up with what you see, I can try to take a peek at the output to see why you might be encountering issues. Cheers!

**Comment by rh3xp** [comment]
Hey Vincent,
Even after I removed the `try/except` the error persists.

![1](https://user-images.githubusercontent.com/11832723/34083305-2d0305c8-e394-11e7-822b-e39ade1a8afe.png)
![2](https://user-images.githubusercontent.com/11832723/34083306-2d4cb556-e394-11e7-9726-ef65ff26de75.png)

Also, I got a mail from google saying 

> Blocked sign-in attempt

**Comment by vprusso** [comment]
Hey Parth, 

Right, removing the try/except was not meant to fix anything, only to give some more detailed information. 

Okay, here's what I think it happening. I imagine you did not set the settings in your Gmail account to be less secure. In my tutorial, you'll note that you must navigate to:
https://myaccount.google.com/lesssecureapps

And turn off the extra security. Did you do this? In my YouTube tutorial, you'll note that this is required
https://www.youtube.com/watch?v=mP_Ln-Z9-XY

Let me know if you did indeed disable this setting, and we can continue diagnosing why this might not be working for you. Cheers!

**Comment by rh3xp** [comment]
Yeah. I just enabled the setting in my account and it works like charm! :100: 
Secondly, I did not know about your youtube channel. Will surely check it out!

**Comment by vprusso** [comment]
Oh, excellent! I tried to make that a little more clear on my Github page for the "youtube_tutorials" repo so others don't get stuck on the same issue. Hopefully, it's more clear now. Thanks again for commenting all the same though!
