### ISSUE TITLE
TypeError: __init__() missing 2 required positional arguments: 'fetched_tweets_filename' and 'hash_tag_list'

### ISSUE THREAD

**Issue by Sumanshu-Nankana** [vprusso/youtube_tutorials#11]
twitter_streamer = TwitterStreamer()
    twitter_streamer.stream_tweets(fetched_tweets_filename, hash_tag_list)

Hello Sir, Looks you are calling TwitterStreamer() class and stream_tweets function of same class
But, fetched_tweets_filename and hash_tag_list are getting initialized in 

class StdOutListener(StreamListener):
    """
    This is a basic listener that just prints received tweets to stdout.
    """
    def __init__(self, fetched_tweets_filename):
        self.fetched_tweets_filename = fetched_tweets_filename

**Comment by vprusso** [comment]
You're using this completely incorrectly. There is a difference between the `__init__` method and what you created as `init`
