### ISSUE TITLE
Operator problem while counting the characters 

### ISSUE THREAD

**Issue by makifay** [vprusso/youtube_tutorials#12]
There is an operator error in the first loop of the second solution (line 49) at the following link: 
algorithms/string_processing/is_permutation.py
` d[i] -= 1`  should be ` d[i] += 1` 
Because the count value of each char should be increased at first.  And then we can check whether it is in the dictionary and decrease the count value in the second loop.

**Comment by vprusso** [comment]
Can you give an example of where the `d[i] -= 1` fails where the `d[i] += 1` does not?

**Comment by makifay** [comment]
At first glance, outputs of the following test cases are inconsistent in the current code;
first output is true while the second is false.
`print(is_perm_1(is_permutation_1, is_permutation_2))
print(is_perm_2(is_permutation_1, is_permutation_2))`

**Comment by makifay** [comment]
Also l think logics are the same between is_permutation and is_anagram.  However, increment operation is applied in the is_anagram while counting the chars like that: 
`ht[i] += 1`

**Comment by vprusso** [comment]
Ah, true enough. What a silly mistake on my part. Thank you for point that out. I've gone ahead and fixed the issue. Thank you!
