### ISSUE TITLE
name corrections 

### ISSUE THREAD

**Issue by makifay** [vprusso/youtube_tutorials#14]
There are minor typos on string names of test cases in the following code: 
algorithms/string_processing/is_unique.py 
They should be as bold fonts like that:
print(is_unique_1(unique_str)) 
print(is_unique_1(**non_unique_str**)) 
print(is_unique_2(**unique_str**))
print(is_unique_2(non_unique_str))

**Comment by vprusso** [comment]
Fixed. Thanks again! :)
