### ISSUE TITLE
Function gives wrong result on some edge cases 

### ISSUE THREAD

**Issue by makifay** [vprusso/youtube_tutorials#15]
The third function in the following code gives the wrong result for some inputs:
data_structures/arrays/two_sum.py 

For instance, if we only change the input A[0]=5 as `A = [5, 1, 2, 4, 7, 11]` 
The output will be: 
_2 11
True
2 11
True
False_

One fix may be like the following change: (yet l didn't test it in detailed)
`while i < j:`   to `while i < len(A):`

**Comment by vprusso** [comment]
We assume that the integers we are given are sorted though.
