### ISSUE TITLE
Accessing tweets more than 20

### ISSUE THREAD

**Issue by apoorvatipre** [vprusso/youtube_tutorials#17]
As mentioned in  API references of tweepy module, only 20 most rencent tweets are accessible by the method API.user_timeline.I need to access large amount of tweets but I am not able to.Is there any way that it could be done?
I entered count=50 but it is not working.
Your help is much appreciated.

**Comment by vprusso** [comment]
This is not the place for this comment. This is a question, not an issue with the software.
