### ISSUE TITLE
bitonic peak code

### ISSUE THREAD

**Issue by brainwave-bruteforce** [vprusso/youtube_tutorials#18]
hey, in the video you wrote the line
`mid_left = A[mid - 1] if mid - 1 > 0 else float("-inf")`
but in the code on github, the minus sign is missing, which I think leads to bad results?
another thing that's a bit confusing is wikipedia says a bitonic sequence is strictly increasing or decreasing, 1 < 3 > 2
but the code notes in both cases lists the elements as nondecreasing etc.. x_1 <= x_2 >= x_3
the rest of the code is aligned with the wikipedia definition.

**Comment by vprusso** [comment]
Can you please reference the specific file you are referring to?

**Comment by brainwave-bruteforce** [comment]
https://github.com/vprusso/youtube_tutorials/blob/master/algorithms/search_algorithms/binary_search/find_bitonic_peak.py

**Comment by vprusso** [comment]
Thanks. I updated the comments and also added in the minus sign that was present in the video, yet somehow not so in the file on my GitHub. Thanks for pointing that out.
