### ISSUE TITLE
line outside the loop

### ISSUE THREAD

**Issue by saiprasannasastry** [vprusso/youtube_tutorials#19]
https://github.com/vprusso/youtube_tutorials/blob/1ff1524c35a94be467ec72fb8b701df352ae1c82/technical_interview/string_compression.py#L23

The line is inline with the for loop and it still compiles.
Not a bug ; its just a doubt.
Its like writing
```
for i in range(5):
print(i)
```

**Comment by vprusso** [comment]
I don't understand. This line is *not* inline with the `for` loop. 

This isn't like the example you provided either, so perhaps you have a misunderstanding?

**Comment by saiprasannasastry** [comment]
i understood the logic clearly, 
correct me if i am wrong,here , both of agree that line 23 is not indented into the for loop.
That line is accessing i, but isn't i local for the forloop? my question is how is i getting the last value,
I've seen many people on the youtube channel ask the question as well.
perhaps changing  line 23 to `comp_str += input_str[-1] + str(count)` would make more sense. I am just not able to understand how line23 is accessing i, since it is not indented inside the loop. If it still feels like my misunderstanding, please close the comment :). I just want to know how that i is being set to the last index of the array

**Comment by vprusso** [comment]
The line does not need to be in the for loop. If you print out `i` before line 23, you will see the variable `i` is still accessible, and refers to the last index obtained in the `for` loop.

**Comment by saiprasannasastry** [comment]
Thanks :)
