### ISSUE TITLE
craigslist script error on line 8

### ISSUE THREAD

**Issue by zentech** [vprusso/youtube_tutorials#8]
I'm getting this error on line 18 when I run the script (same exact script)
 File "craiglist_scrapper.py", line 18
    self.url = f"https://{location}.craigslist.org/search/sss?search_distance={radius}&postal={postal}&max_price={max_price}"
                                                                                                                            ^
SyntaxError: invalid syntax

**Comment by vprusso** [comment]
Are you running using Python3?

**Comment by OsamaJalil** [comment]
What do you recommend, should we run it with Python 3 or 2 ?

**Comment by vprusso** [comment]
Python3. You can't use functional strings with Python2.

**Comment by OsamaJalil** [comment]
Okay. Thank you 🙂
